### ISSUE TITLE
Have skeleton spin when Thrown

### ISSUE THREAD

**Issue by Sean-Nishi** [Sean-Nishi/M1Wengine#195]
When player collides with skeleton "Throw" option send skeleton rotating and flying off screen. Unloads assets when flying skeleton is off screen

when state is thrown, stop current animation, start spinning 

use player's animation for spinning, this require a refactor from player into character

player image rotation will be either merged with other image rotation or as a separate method.

**Comment by owalk** [comment]
Spinning looks weird, im making it rotate 180 degrees when thrown
