### ISSUE TITLE
Fix speed setting bug

### ISSUE THREAD

**Issue by owalk** [Sean-Nishi/M1Wengine#324]
When speed is not set to 1, the behavior does not appear to be correct. Debug and resolve this issue so any speed can be used.

Speed set to 2 on minotaurs does not work when they run away.
They also seem to be more than twice as fast on patrol.

**Comment by Sean-Nishi** [comment]
Requires debugging skills! This is a test

**Comment by owalk** [comment]
Seems like i was crazy before. Speed looks like it is working as intended, but the mechanics might need adjusting.

I suggest a finer scope of control over the speed. Continue to use ints, but have each int represent a smaller change in speed adjustment

**Comment by owalk** [comment]
The bug is not as described above: UPdate

For certain states, speed is hardcoded.
Be based off of character speed instead

**Comment by Sean-Nishi** [comment]
Issue partly completed in #348 when adding in self.DEFAULT_SPEED. Make sure it is referenced in all locations instead of magic numbers
