### ISSUE TITLE
Fix minotaur charge method

### ISSUE THREAD

**Issue by Sean-Nishi** [Sean-Nishi/M1Wengine#348]
Minotaur only charges on patrol directions (maybe)
Compass direction being changed after charge state is set. Or charge state not being implemented properly.

Find where compass is being overwritten when charging.

**Comment by Sean-Nishi** [comment]
Look at charge_movement() method in NPC

**Comment by owalk** [comment]
Change the test map, and remove all but a single minotaur.
Remove all other entities, just while testing, leave 1 player, 1 minotaur, and 1 damsel.

place the damsel where the minotaur radar can see it, or expand the radar radar. Just make testing faster.


Examine the charge_movement function extremely closely, step through it in the debugger

Check that the compass direction is set correctly

rotate compass to target sprite should set and save a direction
direction should never be changed until charge is resolved

It is probably changing

find out where
